version: "3.9"

services:
  hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-hbbs
    restart: unless-stopped
    command: hbbs
    volumes:
      - rustdesk-data:/root
    ports:
      - "21114:21114"
      - "21115:21115"
      - "21116:21116/tcp"
      - "21116:21116/udp"
      - "21118:21118"

  hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-hbbr
    restart: unless-stopped
    command: hbbr
    volumes:
      - rustdesk-data:/root
    ports:
      - "21117:21117"
      - "21119:21119"

volumes:
  rustdesk-data:
    driver: local
